test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,7 +47,7 @@ jobs:
           echo "Listing files in project root:"
           ls -l
           echo "Listing files in /src/js folder:"
-          ls -l dist || echo "dist folder not found"
+          ls -l /src/js || echo "dist folder not found"
 
       - name: Install Surge
         run: npm install --global surge
